DROP FUNCTION IF EXISTS GET_PERIODO;
DELIMITER //
CREATE FUNCTION GET_PERIODO(fecha DATE)
	RETURNS VARCHAR(20)
BEGIN 
	DECLARE periodo INT DEFAULT 0;
		RETURN (SELECT id_periodo FROM periodo WHERE anio= YEAR(fecha) AND mes = MONTH(fecha));

END//
DELIMITER;