SET GLOBAL event_scheduler = ON;

DROP EVENT IF EXISTS TAREA_GENERAR_CARTERA_COBRO;

CREATE EVENT TAREA_GENERAR_CARTERA_COBRO 
ON SCHEDULE EVERY 1 DAY STARTS CONCAT_WS(" ",CURDATE(), "05:00:00")
ON COMPLETION NOT PRESERVE ENABLE 
DO 

CALL COBRO_DIA_PROC_CALCULAR();